language: node_js
node_js:
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
script: npm test
notifications:
  slack: vinyl-hq:VKCjfsyXs4aCjZQLXXlLIp67
